### ISSUE TITLE
Requirements for analysis and charts

### ISSUE THREAD

**Issue by peterdesmet** [Datafable/gbif-data-licenses#13]
I [sketched the basic outline for the post](https://github.com/peterdesmet/peterdesmet.github.com/blob/dev/_source/posts/2013/analyzing-gbif-licenses.md), and these are what I think, the summary data and charts we need. I'll break these up in several issues.
- [x] Standard license use: #14
- [x] Standard licenses used: #15 
- [x] Restrictions within GBIF context: #16 
- [x] Restrictions outside GBIF context: #16
